const WORLD_KEYS=['exp','level','energy','companions','correctAnswers','attempts','streak','bestStreak','lastPlayed','unitProgress'];
const n=(v,d=0)=>Number.isFinite(Number(v))&&Number(v)>=0?Math.floor(Number(v)):d;
function loadData(){let c=[];try{c=JSON.parse(localStorage.getItem('companions')||'[]')}catch(_){};return{exp:n(localStorage.getItem('exp')),level:Math.max(1,n(localStorage.getItem('level'),1)),energy:n(localStorage.getItem('energy')),companions:Array.isArray(c)?c.filter(x=>x&&x.id):[],correctAnswers:n(localStorage.getItem('correctAnswers')),attempts:n(localStorage.getItem('attempts')),streak:n(localStorage.getItem('streak')),bestStreak:n(localStorage.getItem('bestStreak')),lastPlayed:localStorage.getItem('lastPlayed')||'',unitProgress:(()=>{try{let p=JSON.parse(localStorage.getItem('unitProgress')||'{}');return p&&typeof p==='object'&&!Array.isArray(p)?p:{};}catch(_){return {};}})()}}
function saveData(d){['exp','level','energy','correctAnswers','attempts','streak','bestStreak','lastPlayed'].forEach(k=>localStorage.setItem(k,String(d[k]??'')));localStorage.setItem('companions',JSON.stringify(d.companions||[]));localStorage.setItem('unitProgress',JSON.stringify(d.unitProgress||{}))}
function unitId(){let m=location.pathname.match(/unit([1-6])\\.html/);return m?'unit'+m[1]:null}
function addRewards(exp,energy){let d=loadData(),id=unitId();d.exp+=n(exp);d.energy+=n(energy);d.correctAnswers++;d.attempts++;d.streak++;d.bestStreak=Math.max(d.bestStreak,d.streak);if(id){let p=d.unitProgress[id]||{correct:0,attempts:0,mastery:0};p.correct++;p.attempts++;p.mastery=Math.min(100,Math.round(p.correct/20*100));d.unitProgress[id]=p}d.lastPlayed=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});let levelUp=false;while(d.exp>=d.level*100){d.exp-=d.level*100;d.level++;levelUp=true}saveData(d);return{leveledUp:levelUp,newLevel:d.level}}
function recordMistake(){let d=loadData(),id=unitId();d.attempts++;d.streak=0;if(id){let p=d.unitProgress[id]||{correct:0,attempts:0,mastery:0};p.attempts++;d.unitProgress[id]=p}saveData(d)}
function resetData(){if(confirm('学習記録とバッヂのコレクションをリセットしますか？')){WORLD_KEYS.forEach(k=>localStorage.removeItem(k));location.reload()}}
function injectWorldStatus(){if(document.body.dataset.home==='true'||document.querySelector('.world-status'))return;let d=loadData(),e=document.createElement('div');e.className='world-status';e.innerHTML=`⭐ Lv.${d.level}　⚡ ${d.energy}　🔥 ${d.streak}れんぞく　<a href="index.html">ホーム</a>`;Object.assign(e.style,{textAlign:'center',padding:'8px',fontWeight:'800'});document.body.prepend(e)}
function injectNavi(){if(document.querySelector('.navi-card'))return;const names=['riku','sora','kai','saku','tsuki','nami'],jp=['りく','そら','かい','さく','つき','なみ'],file=['07-encouraging.png','02-happy.png','04-idea.png','01-normal-smile.png','08-celebrating.png','03-thinking.png'];let u=unitId(),i=u?Number(u.slice(-1))-1:Math.floor(Math.random()*6),base='https://tt-sensei.github.io/navi-character-/assets/characters/';let box=document.createElement('aside');box.className='navi-card';box.innerHTML=`<img src="${base}${names[i]}/expressions/${file[i]}" alt="${jp[i]}"><div><b>${jp[i]}だよ！</b><span>${u?'いっしょに かんがえよう！':'もんだいに ちょうせんしよう！'}</span></div>`;document.body.prepend(box)}
document.addEventListener('DOMContentLoaded',()=>{injectWorldStatus();injectNavi()});
