const WORLD_KEYS=['exp','level','energy','companions','correctAnswers','attempts','streak','bestStreak','lastPlayed','unitProgress'];
const n=(v,d=0)=>Number.isFinite(Number(v))&&Number(v)>=0?Math.floor(Number(v)):d;
function loadData(){let c=[];try{c=JSON.parse(localStorage.getItem('companions')||'[]')}catch(_){};return{exp:n(localStorage.getItem('exp')),level:Math.max(1,n(localStorage.getItem('level'),1)),energy:n(localStorage.getItem('energy')),companions:Array.isArray(c)?c.filter(x=>x&&x.id):[],gachaCount:n(localStorage.getItem('gachaCount')),correctAnswers:n(localStorage.getItem('correctAnswers')),attempts:n(localStorage.getItem('attempts')),streak:n(localStorage.getItem('streak')),bestStreak:n(localStorage.getItem('bestStreak')),lastPlayed:localStorage.getItem('lastPlayed')||'',unitProgress:(()=>{try{let p=JSON.parse(localStorage.getItem('unitProgress')||'{}');return p&&typeof p==='object'&&!Array.isArray(p)?p:{};}catch(_){return {};}})()}}
function saveData(d){['exp','level','energy','gachaCount','correctAnswers','attempts','streak','bestStreak','lastPlayed'].forEach(k=>localStorage.setItem(k,String(d[k]??'')));localStorage.setItem('companions',JSON.stringify(d.companions||[]));localStorage.setItem('unitProgress',JSON.stringify(d.unitProgress||{}))}
function unitId(){let m=location.pathname.match(/unit([1-6])\.html/);return m?'unit'+m[1]:null}
function addRewards(exp,energy){let d=loadData(),id=unitId();d.exp+=n(exp);d.energy+=n(energy);d.correctAnswers++;d.attempts++;d.streak++;d.bestStreak=Math.max(d.bestStreak,d.streak);if(id){let p=d.unitProgress[id]||{correct:0,attempts:0,mastery:0};p.correct++;p.attempts++;p.mastery=Math.min(100,Math.round(p.correct/20*100));d.unitProgress[id]=p}d.lastPlayed=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'});let levelUp=false;while(d.exp>=d.level*100){d.exp-=d.level*100;d.level++;levelUp=true}saveData(d);return{leveledUp:levelUp,newLevel:d.level}}
function recordMistake(){let d=loadData(),id=unitId();d.attempts++;d.streak=0;if(id){let p=d.unitProgress[id]||{correct:0,attempts:0,mastery:0};p.attempts++;d.unitProgress[id]=p}saveData(d)}
function resetData(){if(confirm('学習記録とバッヂのコレクションをリセットしますか？')){WORLD_KEYS.forEach(k=>localStorage.removeItem(k));location.reload()}}
function injectWorldStatus(){if(document.body.dataset.home==='true'||document.querySelector('.world-status'))return;let d=loadData(),e=document.createElement('div');e.className='world-status';e.innerHTML=`⭐ Lv.${d.level}　⚡ ${d.energy}　🔥 ${d.streak}れんぞく　<a href="index.html">ホーム</a>`;Object.assign(e.style,{textAlign:'center',padding:'8px',fontWeight:'800'});document.body.prepend(e)}
function naviInfo(){const names=['riku','sora','kai','saku','tsuki','nami'],jp=['りく','そら','かい','さく','つき','なみ'],i=unitId()?Number(unitId().slice(-1))-1:0;return{base:'https://tt-sensei.github.io/navi-character-/assets/characters/',name:names[i],jp:jp[i]}}
function injectNavi(){if(document.querySelector('.navi-card'))return;const names=['riku','sora','kai','saku','tsuki','nami'],jp=['りく','そら','かい','さく','つき','なみ'],file=['07-encouraging.png','02-happy.png','04-idea.png','01-normal-smile.png','08-celebrating.png','03-thinking.png'];let u=unitId(),i=u?Number(u.slice(-1))-1:Math.floor(Math.random()*6),base='https://tt-sensei.github.io/navi-character-/assets/characters/';let style=document.createElement('style');style.textContent='.navi-card{display:flex;align-items:center;gap:10px;max-width:520px;margin:0 auto 12px;padding:8px 14px;background:#ffffffdd;border:2px solid #90caf9;border-radius:18px;box-shadow:0 4px 0 #1565c033;text-align:left;font-size:.9rem}.navi-card img{width:52px;height:52px;object-fit:contain;flex:none}.navi-card b{display:block;color:#1565c0}.navi-card span{display:block;color:#546e7a;font-weight:700;margin-top:2px}@media(max-width:480px){.navi-card{margin-bottom:8px;padding:5px 10px}.navi-card img{width:44px;height:44px}}';document.head.appendChild(style);let box=document.createElement('aside');box.className='navi-card';box.innerHTML=`<img src="${base}${names[i]}/expressions/${file[i]}" alt="${jp[i]}" style="width:52px;height:52px;object-fit:contain;display:block"><div><b>${jp[i]}だよ！</b><span>${u?'いっしょに かんがえよう！':'もんだいに ちょうせんしよう！'}</span></div>`;document.body.prepend(box)}
function showNaviFeedback(type){if(!document.getElementById('navi-feedback-style')){let s=document.createElement('style');s.id='navi-feedback-style';s.textContent='.navi-feedback{height:auto!important;min-height:56px;text-align:center;font-size:1rem!important;line-height:1.1}.navi-feedback-content{display:inline-flex;align-items:center;gap:1px;vertical-align:middle}.navi-feedback-content img{width:52px;height:52px;object-fit:contain;flex:none}.navi-feedback-content span{font-weight:900}';document.head.appendChild(s)}const feedback=document.getElementById('feedback');if(!feedback)return;const info=naviInfo(),file=type==='correct'?'08-celebrating.png':'07-encouraging.png';feedback.innerHTML=`<span class="navi-feedback-content"><img src="${info.base}${info.name}/expressions/${file}" alt="" style="width:52px;height:52px;object-fit:contain;display:block"><span>${type==='correct'?'せいかい！':'もういちど！'}</span></span>`;feedback.classList.remove('wrong','correct');feedback.classList.add(type==='correct'?'correct':'wrong','navi-feedback')}
// Web配信用の軽量画像を優先して読み込む
const _naviBase='https://tt-sensei.github.io/navi-character-/assets/web/characters/';
const _naviFiles=['07-encouraging.webp','02-happy.webp','04-idea.webp','01-normal-smile.webp','08-celebrating.webp','03-thinking.webp'];
const _oldNaviInfo=naviInfo,_oldInjectNavi=injectNavi,_oldShowNaviFeedback=showNaviFeedback;
naviInfo=function(){const x=_oldNaviInfo();return{...x,base:_naviBase}};
injectNavi=function(){_oldInjectNavi();const img=document.querySelector('.navi-card img');if(img){const i=unitId()?Number(unitId().slice(-1))-1:0;const names=['riku','sora','kai','saku','tsuki','nami'];img.src=`${_naviBase}${names[i]}/expressions/${_naviFiles[i]}`}};
showNaviFeedback=function(type){_oldShowNaviFeedback(type);const img=document.querySelector('#feedback .navi-feedback-content img');if(img){const info=naviInfo();img.src=`${info.base}${info.name}/expressions/${type==='correct'?'08-celebrating.webp':'07-encouraging.webp'}`}};
document.addEventListener('DOMContentLoaded',()=>{injectWorldStatus();injectNavi()});
